export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const EXPENSES_REQUEST = 'EXPENSES_REQUEST';
export const EXPENSES_SUCCESS = 'EXPENSES_SUCCESS';
export const EXPENSES_FAILURE = 'EXPENSES_FAILURE';

export const AVERAGE_REQUEST = 'AVERAGE_REQUEST';
export const AVERAGE_SUCCESS = 'AVERAGE_SUCCESS';
export const AVERAGE_FAILURE = 'AVERAGE_FAILURE';

export const DATES_REQUEST = 'DATES_REQUEST';
export const DATES_SUCCESS = 'DATES_SUCCESS';
export const DATES_FAILURE = 'DATES_FAILURE';

export const CSV_REQUEST = 'CSV_REQUEST';
export const CSV_SUCCESS = 'CSV_SUCCESS';
export const CSV_FAILURE = 'CSV_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const APPROVE_USERS_REQUEST = 'APPROVE_USERS_REQUEST';
export const APPROVE_USERS_SUCCESS = 'APPROVE_USERS_SUCCESS';
export const APPROVE_USERS_FAILURE = 'APPROVE_USERS_FAILURE';

export const AUTHORIZE_USERS_REQUEST = 'AUTHORIZE_USERS_REQUEST';
export const AUTHORIZE_USERS_SUCCESS = 'AUTHORIZE_USERS_SUCCESS';
export const AUTHORIZE_USERS_FAILURE = 'AUTHORIZE_USERS_FAILURE';

export const RESET_EDITED_STATE = 'RESET_EDITED_STATE';